version: 2.1

commands:
  tester:
    steps:
      # local:
      #    comment: - checkout
      #    run: circleci config process .circleci/config.yml  > .circleci/config2.yml && circleci local execute -c .circleci/config2.yml  --job test_1_1 -v $PWD:/home/circleci/app
      - checkout
      - run:
          name: Build image.
          command: sudo docker build -t tammoippen/kongcli:latest .
      - run:
          name: Start kong and verify it is working.
          command: |
            set -x
            env
            sudo -E docker-compose --project-name tests up -d
            sleep 5
            sudo docker run --network container:kong --rm -it \
              byrnedo/alpine-curl --retry 20 --retry-delay 1 --retry-connrefused http://localhost:8001/
      - run:
          name: Testing.
          command: |
            sudo docker run --rm -it \
                            --network container:kong \
                            -v $PWD:/app \
                            tammoippen/kongcli:latest make ci
      - run:
          name: Stop kong.
          when: always
          command: sudo docker-compose --project-name tests down --volumes
      - run:
          name: Build sdist.
          command: |
            sudo docker run --rm -it \
                            -v $PWD:/app \
                            --entrypoint /bin/sh \
                            tammoippen/kongcli:latest poetry build -vvv -f sdist
      - store_artifacts:
          path: ~/app/dist
          destination: dist
      - store_artifacts:
          path: ~/app/cov_html
          destination: cov_html
      - run:
          name: Coverage
          command: |
            sudo docker run --rm -it \
                            -v $PWD:/app \
                            --entrypoint /bin/sh \
                            tammoippen/kongcli:latest poetry run coveralls

executors:
  default:
    working_directory: ~/app
    machine:
      docker_layer_caching: true

jobs:
  test_13:
    executor:
      name: default
    environment:
      KONG_VERSION_TAG: 0.13
    steps:
      - tester
  test_14:
    executor:
      name: default
    environment:
      KONG_VERSION_TAG: 0.14
    steps:
      - tester
  test_15:
    executor:
      name: default
    environment:
      KONG_VERSION_TAG: 0.15
    steps:
      - tester
  test_1_0:
    executor:
      name: default
    environment:
      KONG_VERSION_TAG: 1.0
      KONG_MIGRATION_CMD: bootstrap
    steps:
      - tester
  test_1_1:
    executor:
      name: default
    environment:
      KONG_VERSION_TAG: 1.1
      KONG_MIGRATION_CMD: bootstrap
    steps:
      - tester
  test_1_2:
    executor:
      name: default
    environment:
      KONG_VERSION_TAG: 1.2
      KONG_MIGRATION_CMD: bootstrap
    steps:
      - tester

  deploy_job:
    docker:
      - image: circleci/python:3.6.8
    description: "Deploy kongcli to pypi."
    steps:
      - checkout

      - run:
          name: Set PATH.
          command: |
            echo 'export PATH=$HOME/.local/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Pre-install
          command: |
            pip install --user poetry
            poetry build -vvv -f sdist
            poetry publish -vvv -n -u tammoippen -p $PYPI_PASS

workflows:
  version: 2.1
  test_and_deploy:
    jobs:
      - test_13:
        filters:
          tags:
            only: /.*/
      - test_14:
        filters:
          tags:
            only: /.*/
      - test_15:
        filters:
          tags:
            only: /.*/
      - test_1_0:
        filters:
          tags:
            only: /.*/
      - test_1_1:
        filters:
          tags:
            only: /.*/
      - test_1_2:
        filters:
          tags:
            only: /.*/
      - deploy_job:
          requires:
            - test_13
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
