version: 2.1

commands:
  tester:
    steps:
      - checkout
      - run:
          name: Build image.
          command: sudo docker build -t tammoippen/kongcli:latest .
      - run:
          name: Start kong and verify it is working.
          command: |
            set -x
            env
            sudo -E docker-compose --project-name tests up -d
            sleep 10
            sudo docker run --network container:kong --rm -it \
              --entrypoint curl \
              tammoippen/kongcli:latest --retry 20 --retry-delay 1 --retry-connrefused http://localhost:8001/
      - run:
          name: Testing.
          command: |
            sudo docker run --rm -it \
                            --network tests_default \
                            -e KONG_HOST=kong \
                            -e KONG_PG_HOST=kong_database \
                            -e HTTPBIN_HOST=httpbin \
                            -e HTTPBIN_PORT=80 \
                            -v $PWD:/app \
                            --entrypoint make \
                            tammoippen/kongcli:latest ci
      - run:
          name: Stop kong.
          when: always
          command: sudo docker-compose --project-name tests down --volumes
      - run:
          name: Build sdist.
          command: |
            sudo docker run --rm -it \
                            -v $PWD:/app \
                            --entrypoint poetry \
                            tammoippen/kongcli:latest build -vvv -f sdist
      - store_artifacts:
          path: ~/app/dist
          destination: dist
      - store_artifacts:
          path: ~/app/cov_html
          destination: cov_html
      - run:
          name: Coverage
          command: |
            sudo docker run --rm -it \
                            -v $PWD:/app \
                            -e COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN \
                            --entrypoint make \
                            tammoippen/kongcli:latest coveralls

executors:
  default:
    working_directory: ~/app
    machine:
      image: circleci/classic:latest
      # docker_layer_caching: true

jobs:
  test_13: &test-job
    executor:
      name: default
    environment:
      KONG_VERSION_TAG: '0.13'
      KONG_MIGRATION_CMD: up
    steps:
      - tester
  test_14:
    <<: *test-job
    environment:
      KONG_VERSION_TAG: '0.14'
      KONG_MIGRATION_CMD: up
  test_15:
    <<: *test-job
    environment:
      KONG_VERSION_TAG: '0.15'
  test_1_0:
    <<: *test-job
    environment:
      KONG_VERSION_TAG: '1.0'
  test_1_1:
    <<: *test-job
    environment:
      KONG_VERSION_TAG: '1.1'
  test_1_2:
    <<: *test-job
    environment:
      KONG_VERSION_TAG: '1.2'
  test_1_3:
    <<: *test-job
    environment:
      KONG_VERSION_TAG: '1.3'
  test_1_4:
    <<: *test-job
    environment:
      KONG_VERSION_TAG: '1.4'
  test_1_5:
    <<: *test-job
    environment:
      KONG_VERSION_TAG: '1.5'
  test_2_0:
    <<: *test-job
    environment:
      KONG_VERSION_TAG: '2.0'
  test_2_1:
    <<: *test-job
    environment:
      KONG_VERSION_TAG: '2.1'

workflows:
  version: 2.1
  test_and_deploy:
    jobs:
      - test_13
      - test_14
      - test_15
      - test_1_0
      - test_1_1
      - test_1_2
      - test_1_3
      - test_1_4
      - test_1_5
      - test_2_0
      - test_2_1
