version: 2.0

jobs:

  build:
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Start kong and verify it is working
          command: |
            set -x
            sudo docker-compose up -d
            sudo docker run --network container:kong \
              byrnedo/alpine-curl --retry 10 --retry-delay 1 --retry-connrefused http://localhost:8001/
